openapi: 3.0.3
info:
  title: Swagger Animal store - OpenAPI 3.0
  version: 1.0.11
paths:
  /animal:
    get:
      operationId: findAnimal
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Animal'
components:
  schemas:
    Animal:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
        type:
          oneOf:
            - $ref: '#/components/schemas/AnimalType'
        breed:
          oneOf:
            - $ref: '#/components/schemas/AnimalBreed'
    AnimalBreed:
      properties:
        breedName:
          type: string
    AnimalType:
      type: string
      enum:
        - friendly
        - unfriendly